### ISSUE TITLE
Change Ratio of BKM:Energy from 10:1 to 1:200

### ISSUE THREAD

**Issue by mpamiesi** [spaceriders-web3/frontend#233]
![a](https://user-images.githubusercontent.com/113771379/212490651-b805a403-df5d-48b4-8723-3c7d576b8bce.PNG)

**Comment by devjoseruiz** [comment]
Note that it has to be changed in the backend as well.

**Comment by devjoseruiz** [comment]
Done. Check PR.

**Comment by devjoseruiz** [comment]
Task complete. This issue can be closed @mpamiesi @redigaffi.
