### ISSUE TITLE
Add a String of the $BKM contract in the Frontend, to easily add the Token to Metamask/Face Wallet

### ISSUE THREAD

**Issue by mpamiesi** [spaceriders-web3/frontend#234]

**Comment by devjoseruiz** [comment]
Where would you like to place this element?

**Comment by mpamiesi** [comment]
@devjoseruiz It should be placed within the swap tool and/or in BKM pop-up when you press BKM logo for deposit/withdraw. With a functionality of copying by clicking.

**Comment by devjoseruiz** [comment]
Check PR https://github.com/spaceriders-web3/frontend/pull/276
