### ISSUE TITLE
Add Dapp Play Store logo to Landing Page

### ISSUE THREAD

**Issue by mpamiesi** [spaceriders-web3/frontend#266]
Logo: ![DPS Logo](https://user-images.githubusercontent.com/113771379/220610916-1fce2ad3-4151-4df3-850f-94ce3622b180.png)

Website that user should be redirected to when clicking the logo: https://www.dapp-playstore.com/

**Comment by devjoseruiz** [comment]
Done. Check PR: https://github.com/spaceriders-web3/frontend/pull/271
